<?php

/**
 * @file
 * Contains jsondata.module.
 */

/**
 * HB.
 */
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;


/*
*
* Implements hook_form_FORM-ID_alter
* This is to Add New field in Site information page
* By default, jsondata.settings siteapikey will be empty.
*/

function jsondata_form_system_site_information_settings_alter(&$form, FormStateInterface $form_state) {

  $siteapikey = '';
  $siteapikey = \Drupal::config('jsondata.settings')->get('siteapikey');
  $form['site_information']['siteapikey'] = array(
    '#type' => 'textfield',
    '#title' => t('Your Site API Key'),
    '#default_value' => $siteapikey,
    '#placeholder' => t('No API Key yet'),
  );

  $form['actions']['submit']['#value'] = t('Update Configuration');

  //Submit handler to store siteapikey value into jsondata.setting
  $form['#submit'][] = 'jsondata_siteinformation_submit_handler';

}

//Submit handler to store siteapikey value into jsondata.setting
function jsondata_siteinformation_submit_handler(&$form, FormStateInterface $formState) {
 
  if( false == empty( $form['site_information']['siteapikey']['#value'] ) && $form['site_information']['siteapikey']['#value'] != \Drupal::config('jsondata.settings')->get('siteapikey') ) {

    \Drupal::configFactory()->getEditable('jsondata.settings')
      ->set('siteapikey', $form['site_information']['siteapikey']['#value'])
      ->save();
    drupal_set_message($form['site_information']['siteapikey']['#value'].' - Site API Key updated.');
  }
}